### ISSUE TITLE
SSH-Key creation

### ISSUE THREAD

**Issue by Ajowan84** [threatpatrols/opnsense-plugin-autossh#1]
Hi,

This plugin is my dream but it does not work.
I can not create an ssh key in the Keys tab
After pressing save, the key does not appear in the list
My Opnsense version in 19.7-amd64 and freeBSD is 11.2-RELEASE-p11-HBSD

I attach a capture of the ssh key generation window
![2019-10-13_191847](https://user-images.githubusercontent.com/42247038/66719302-5d9bc600-edee-11e9-8209-46a3bac6efe8.jpg)

**Comment by ndejong** [comment]
Hi @Ajowan84 - sorry to hear you are having a hard time, I don't be able to get myself in front of a n environment to check this out for a few days - are you able to provide any logs or other hints in the short term?  N

**Comment by Ajowan84** [comment]
there is nothing in the log file.

**Comment by Ajowan84** [comment]
Hi,
No suggestion ?
thank,

**Comment by TNT911** [comment]
I have the same issue.  Pity the plugin is flagged as (orphaned).  I'd like to use "authpf", however this is the closest option we have for OPNsense.

**Comment by ndejong** [comment]
Hi, very long time between updates on this

Please check #3 up-to-date packages for OPNsense 21.1 through to the latest 22.7 are available
