### ISSUE TITLE
Working with opnsense 21.1 ?

### ISSUE THREAD

**Issue by PhilippeRaven** [threatpatrols/opnsense-plugin-autossh#2]
Is this plugin totally orphaned ?
Is it working with opnsense 21.1 ?

Thanks for answers

**Comment by ndejong** [comment]
Hi - the plugin is not abandoned, however we do not have enough time to test for each OPNsense release at the moment - if you do happen install and test please do report back, that would be awesome - N

**Comment by PhilippeRaven** [comment]
Hello,
I can try it on my 21.1.
All I have to do is to compile it by following the "build-at-remote.sh" script content ?
Because I don't see any others compilations instructions in this repo.

Thanks

**Comment by PhilippeRaven** [comment]
@ndejong I tried to pkg add https://github.com/verbnetworks/packages/raw/master/opnsense-plugin-autossh/os-autossh-devel-0.1_1.txz but it's still for FreeBSD 11, and now opnsense 21 is based on FreeBSD 12.
So i got the "pkg: wrong architecture: FreeBSD:11:amd64 instead of FreeBSD:12:amd64" message.

**Comment by ndejong** [comment]
Hi @PhilippeRaven 

Long time between updates here; see #3 packages for OPNsense 21.1 through the latest 22.7 are all available.
