### ISSUE TITLE
[INFO] Updating this for OPNSense 21.1.x

### ISSUE THREAD

**Issue by LaurentFough** [threatpatrols/opnsense-plugin-autossh#3]
Hi @ndejong,

This is a plugin for OPNSense that I'm sorely in need of.

I'll start pouring over the code and see about updating it to support 21.1.x, and fire off any questions to you if you can help.

* Do you have a more recent/ non-published code-base that's more supportive of the current OPNSense release?

**Comment by ndejong** [comment]
Better late than never.

The latest packages can be found in `repo.threatpatrols.com` or you can install the `os-threatpatrols` plugin to then install `autossh` from the OPNsense package manager GUI

Read up on `repo.threatpatrols.com` here -
* https://documentation.threatpatrols.com/opnsense/repo/
