### ISSUE TITLE
basic "here's how to get started" docs?

### ISSUE THREAD

**Issue by ppbrown** [threatpatrols/opnsense-plugin-autossh#4]
the readme feature list kindasorta sounds like something I need... but I'm not sure, because I dont see a single usage sample.
I dont see a reference in the README.md
I dont see a "docs" directory.
So I dont even know where to get started.

**Comment by ndejong** [comment]
Hi @ppbrown 

Been a while in the works, you can find documentation here:
* https://documentation.threatpatrols.com/opnsense/plugins/autossh/
